include_recipe "chef-socorro::api"
include_recipe "chef-socorro::collector"
include_recipe "chef-socorro::crashmover"
include_recipe "chef-socorro::monitor"
include_recipe "chef-socorro::processor"
include_recipe "chef-socorro::ui"