include_recipe "socorro::api"
include_recipe "socorro::collector"
include_recipe "socorro::crashmover"
include_recipe "socorro::monitor"
include_recipe "socorro::processor"
include_recipe "socorro::ui"